DexCore/DexCore/Models/CompanySummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DexCore.Models
{
    public class CompanySummary
    {

        public int EmployeeCount { get; set; }
        public int AverageDepartmentEmployeeCount { get; set; }
    }
}

DexCore/DexCore/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DexCore.Models
{
    public class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int EmployeeCount { get; set; }
    }
}

DexCore/DexCore/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DexCore.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Gender Gender { get; set; }
        public bool Fired { get; set; }
        public int GetByDepartmentId { get; internal set; }
    }

    public enum Gender
    {
        Man = 1,
        Woman = 0,
    }
}

DexCore/DexCore/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DexCore.Models;
using DexCore.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DexCore.Controllers
{
    public class DepartmentController: Controller
    {

        private readonly IDepartmentService _departmentService;
        private readonly IOptions<DexCoreOptions> _dexCoreOptions;
        public DepartmentController(IDepartmentService departmentService, IOptions<DexCoreOptions> dexCoreOptions)
        {
            _departmentService = departmentService;
            _dexCoreOptions = dexCoreOptions;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Department Index";
            var departments = await _departmentService.GetAll();
            return View(departments);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Title = "Add Department";
            return View(new Department());
        }

        [HttpPost]
        public async Task<IActionResult> Add(Department model)
        {
            if (ModelState.IsValid)
            {
                await _departmentService.Add(model);
            }
            return RedirectToAction(nameof(Index));
        } 
    }
}

DexCore/DexCore/Controllers/EmployeeController.cs
using DexCore.Models;
using DexCore.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DexCore.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IDepartmentService _departmentService;
        private readonly IEmployeeService _employeeService;

        public EmployeeController(IDepartmentService departmentService, IEmployeeService employeeService)
        {
            _departmentService = departmentService;
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index(int departmentId)
        {
            var department = await _departmentService.GetById(departmentId);
            ViewBag.Title = $"Employees of {department.Name}";
            ViewBag.DepartmentId = departmentId; //Because the view does not contain DepartmentId reference. Hence, the page will get departmentId here. 

            var employees = await _employeeService.GetByDepartmentId(departmentId);
            return View(employees);
        }

        public IActionResult Add(int departmentId)
        {
            ViewBag.Title = "Add Employee";
            return View(new Employee { DepartmentId = departmentId });
        }

        [HttpPost]
        public async Task<IActionResult> Add(Employee model)
        {
            if(ModelState.IsValid)
            {
                await _employeeService.Add(model);
            }
            return RedirectToAction(nameof(Index), new { departmentId = model.DepartmentId });
        }

        public async Task<IActionResult> Fire(int employeeId)
        {
            var employee = await _employeeService.Fire(employeeId);
            return RedirectToAction(nameof(Index), new { departmentId = employee.DepartmentId });
        }
    }
}

DexCore/DexCore/ViewComponents/CompanySummaryViewComponent.cs
using DexCore.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DexCore.ViewComponents
{
    public class CompanySummaryViewComponent : ViewComponent
    {
        private readonly IDepartmentService _departmentService;

        public CompanySummaryViewComponent(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string title)
        {
            ViewBag.Title = title;
            var summary = await _departmentService.GetCompanySummary();
            return View(summary);
        }
    }
}

DexCore/DexCore/Views/Department/Add.cshtml
@using DexCore.Models
@model Department

    <form asp-action="Add">
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="Name" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="Location"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="Location" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="EmployeeCount"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="EmployeeCount" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </div>
    </form>

DexCore/DexCore/Views/Department/DisplayTemplates/Department.cshtml
@using Microsoft.Extensions.Options
@using DexCore
@model DexCore.Models.Department
@inject IOptions<DexCoreOptions> options
    <tr>
        @if (Model.EmployeeCount > options.Value.BoldDepartmentEmployeeCountThreshold)
        {
            <td><strong>@Model.Name</strong></td>
        }
        else
        {
            <td>@Model.Name</td>
        }
        <td>@Model.Location</td>
        <td>@Model.EmployeeCount</td>

        <td>
            <a asp-controller="Employee" asp-action="Index" asp-route-departmentId="@Model.Id">
                Employee
            </a>
        </td>
    </tr>

DexCore/DexCore/Views/Department/Index.cshtml
@using DexCore.Models
@model IEnumerable<Department>
 
<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Employee Count</th>
                <th>Operation</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        @await Component.InvokeAsync("CompanySummary", new { title = "Department Summary"})
        <vc:company-summary title ="Department Summary 2"></vc:company-summary>
    </div>
    <div class="col-md-4 offset-md-2">
        <a asp-action="Add">Add</a>
    </div>
</div>

DexCore/DexCore/Views/Employee/Add.cshtml
@using DexCore.Models
@model Employee

    <form asp-action="Add">
        <input type="hidden" asp-for="DepartmentId" />
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="FirstName"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="FirstName" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <label asp-for="LastName"></label>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="LastName" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 offset-md-2">
                <!-- <label asp-for="Gender"></label> -->
                <select class="form-control" asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()"></select>
            </div>
            <div class="col-md-6">
                <input class="form-control" asp-for="Gender" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </div>
    </form>

DexCore/DexCore/Views/Employee/DisplayTemplates/Employee.cshtml
@model DexCore.Models.Employee
    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
        <td>@Model.Gender</td>
        <td>@(Model.Fired ? "Yes": "")</td>

        <td>
            @if (!Model.Fired)
            {
                <a asp-action="Fire" asp-route-employeeId="@Model.Id">
                    Fire
                </a>
            }
        </td>
    </tr>

DexCore/DexCore/Views/Employee/Index.cshtml
@using DexCore.Models
@model IEnumerable<Employee>

<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Gender</th>
                <th>Is Fired</th>
                <th>Operation</th>
            </tr>
            @Html.DisplayForModel();
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4 offset-md-2">
        <a asp-action="Add" asp-route-departmentId="@ViewBag.DepartmentId">Add</a>
    </div>
</div>

DexCore/DexCore/Views/Shared/Components/CompanySummary/Default.cshtml
@model DexCore.Models.CompanySummary
    <div class="small">
        <div class="row h5">@ViewBag.Title</div>
        <div class="row h3">Company Summary</div>
        <div class="row">
            <div class="col-md-8">Total Employmees</div>
            <div class="col-md-4">@Model.EmployeeCount</div>
        </div>
        <div class="row">
            <div class="col-md-8">Average Employees</div>
            <div class="col-md-4">@Model.AverageDepartmentEmployeeCount</div>
        </div>
    </div>

DexCore/DexCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="css/*" asp-href-exclude="css/all.min.css" />
    </environment>

    <environment include="Production">
        <link rel="stylesheet" asp-href-include="all.min.css" />
    </environment>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <img asp-append-version ="true" alt="Logo" scr ="images/logo.png" style="height:60px;"/> 
            </div>
            <div class="col-md-10">
                <span class="h2">@ViewBag.Title</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
        
    </div>
</body>
</html>